plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bocofi.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.bocofi.app'
        minSdk 24
        targetSdk 36
        versionCode 4
        versionName '1.3'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

task copyWebFiles(type: Copy) {
    from('../..') {
        include 'index.html'
        include 'kiosk/**'
        include 'app/**'
        include 'admin/**'
        include 'assets/**'
    }
    into 'src/main/assets/www'
}
preBuild.dependsOn copyWebFiles
